<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Category::create(['name' =>  'Bolsas Emblocadas MAPA'
, 'slug' => str_slug( 'Bolsas Emblocadas MAPA'
), 'subrubro_id' =>  1  ]);App\Category::create(['name' =>  'Bolsas en Rollo BD MAPA'
, 'slug' => str_slug( 'Bolsas en Rollo BD MAPA'
), 'subrubro_id' =>  2  ]);App\Category::create(['name' =>  'Bolsas de Consorcio BARPLAST'
, 'slug' => str_slug( 'Bolsas de Consorcio BARPLAST'
), 'subrubro_id' =>  3  ]);App\Category::create(['name' =>  'Polietileno con Burbujas'
, 'slug' => str_slug( 'Polietileno con Burbujas'
), 'subrubro_id' =>  4  ]);App\Category::create(['name' =>  'Tripodes para Pizzas'
, 'slug' => str_slug( 'Tripodes para Pizzas'
), 'subrubro_id' =>  5  ]);App\Category::create(['name' =>  'Film Stretch'
, 'slug' => str_slug( 'Film Stretch'
), 'subrubro_id' =>  6  ]);App\Category::create(['name' =>  'Hilos'
, 'slug' => str_slug( 'Hilos'
), 'subrubro_id' =>  7  ]);App\Category::create(['name' =>  'Cubiertos Plasticos'
, 'slug' => str_slug( 'Cubiertos Plasticos'
), 'subrubro_id' =>  8  ]);App\Category::create(['name' =>  'Vasos Plasticos'
, 'slug' => str_slug( 'Vasos Plasticos'
), 'subrubro_id' =>  9  ]);App\Category::create(['name' =>  'Film de PVC'
, 'slug' => str_slug( 'Film de PVC'
), 'subrubro_id' =>  10  ]);App\Category::create(['name' =>  'Papel Muresco'
, 'slug' => str_slug( 'Papel Muresco'
), 'subrubro_id' =>  11  ]);App\Category::create(['name' =>  'Papel Murillo'
, 'slug' => str_slug( 'Papel Murillo'
), 'subrubro_id' =>  12  ]);App\Category::create(['name' =>  'Porta Bobinas de Papel'
, 'slug' => str_slug( 'Porta Bobinas de Papel'
), 'subrubro_id' =>  13  ]);App\Category::create(['name' =>  'Servilletas de Papel'
, 'slug' => str_slug( 'Servilletas de Papel'
), 'subrubro_id' =>  14  ]);App\Category::create(['name' =>  'Sobres de Papel Muresco'
, 'slug' => str_slug( 'Sobres de Papel Muresco'
), 'subrubro_id' =>  15  ]);App\Category::create(['name' =>  'Bandejas Doradas Configraf'
, 'slug' => str_slug( 'Bandejas Doradas Configraf'
), 'subrubro_id' =>  16  ]);App\Category::create(['name' =>  'Vasos Plasticos Trago Largo'
, 'slug' => str_slug( 'Vasos Plasticos Trago Largo'
), 'subrubro_id' =>  17  ]);App\Category::create(['name' =>  'Platos Plasticos'
, 'slug' => str_slug( 'Platos Plasticos'
), 'subrubro_id' =>  18  ]);App\Category::create(['name' =>  'Plastiflechas'
, 'slug' => str_slug( 'Plastiflechas'
), 'subrubro_id' =>  19  ]);App\Category::create(['name' =>  'Cintas de Regalo'
, 'slug' => str_slug( 'Cintas de Regalo'
), 'subrubro_id' =>  20  ]);App\Category::create(['name' =>  'Moños'
, 'slug' => str_slug( 'Moños'
), 'subrubro_id' =>  21  ]);App\Category::create(['name' =>  'Bolsas Riñon Terlizzi'
, 'slug' => str_slug( 'Bolsas Riñon Terlizzi'
), 'subrubro_id' =>  22  ]);App\Category::create(['name' =>  'Libretas'
, 'slug' => str_slug( 'Libretas'
), 'subrubro_id' =>  23  ]);App\Category::create(['name' =>  'Marcadores'
, 'slug' => str_slug( 'Marcadores'
), 'subrubro_id' =>  24  ]);App\Category::create(['name' =>  'Chinches'
, 'slug' => str_slug( 'Chinches'
), 'subrubro_id' =>  25  ]);App\Category::create(['name' =>  'Etiquetas'
, 'slug' => str_slug( 'Etiquetas'
), 'subrubro_id' =>  26  ]);App\Category::create(['name' =>  'Biromes'
, 'slug' => str_slug( 'Biromes'
), 'subrubro_id' =>  27  ]);App\Category::create(['name' =>  'Broches'
, 'slug' => str_slug( 'Broches'
), 'subrubro_id' =>  28  ]);App\Category::create(['name' =>  'Saladitos'
, 'slug' => str_slug( 'Saladitos'
), 'subrubro_id' =>  29  ]);App\Category::create(['name' =>  'Bolsas Camisetas AD'
, 'slug' => str_slug( 'Bolsas Camisetas AD'
), 'subrubro_id' =>  30  ]);App\Category::create(['name' =>  'Bolsas de Arranque en Rollo AD'
, 'slug' => str_slug( 'Bolsas de Arranque en Rollo AD'
), 'subrubro_id' =>  31  ]);App\Category::create(['name' =>  'Bandejas Plasticas Arenales'
, 'slug' => str_slug( 'Bandejas Plasticas Arenales'
), 'subrubro_id' =>  32  ]);App\Category::create(['name' =>  'Bandejas Micro CelPack'
, 'slug' => str_slug( 'Bandejas Micro CelPack'
), 'subrubro_id' =>  33  ]);App\Category::create(['name' =>  'Bandejas de Expandido'
, 'slug' => str_slug( 'Bandejas de Expandido'
), 'subrubro_id' =>  34  ]);App\Category::create(['name' =>  'Bandejas Aluminio Alpac'
, 'slug' => str_slug( 'Bandejas Aluminio Alpac'
), 'subrubro_id' =>  35  ]);App\Category::create(['name' =>  'Blondas de Papel Configraf'
, 'slug' => str_slug( 'Blondas de Papel Configraf'
), 'subrubro_id' =>  36  ]);App\Category::create(['name' =>  'Bolsas con Abrojo y Moño'
, 'slug' => str_slug( 'Bolsas con Abrojo y Moño'
), 'subrubro_id' =>  37  ]);App\Category::create(['name' =>  'Bolsas de Panaderia Envasadas'
, 'slug' => str_slug( 'Bolsas de Panaderia Envasadas'
), 'subrubro_id' =>  38  ]);App\Category::create(['name' =>  'Bolsas de Polipropileno'
, 'slug' => str_slug( 'Bolsas de Polipropileno'
), 'subrubro_id' =>  39  ]);App\Category::create(['name' =>  'Cajas de Carton Común'
, 'slug' => str_slug( 'Cajas de Carton Común'
), 'subrubro_id' =>  40  ]);App\Category::create(['name' =>  'Cajas de Bombones'
, 'slug' => str_slug( 'Cajas de Bombones'
), 'subrubro_id' =>  41  ]);App\Category::create(['name' =>  'Cajas para Masas'
, 'slug' => str_slug( 'Cajas para Masas'
), 'subrubro_id' =>  42  ]);App\Category::create(['name' =>  'Cajas de Pizza Redonda'
, 'slug' => str_slug( 'Cajas de Pizza Redonda'
), 'subrubro_id' =>  43  ]);App\Category::create(['name' =>  'Cajas de Pizza Microcorrugado'
, 'slug' => str_slug( 'Cajas de Pizza Microcorrugado'
), 'subrubro_id' =>  44  ]);App\Category::create(['name' =>  'Maples para Huevos'
, 'slug' => str_slug( 'Maples para Huevos'
), 'subrubro_id' =>  45  ]);App\Category::create(['name' =>  'Cintas de Papel Autoad. PackTape'
, 'slug' => str_slug( 'Cintas de Papel Autoad. PackTape'
), 'subrubro_id' =>  46  ]);App\Category::create(['name' =>  'Cintas de PP Autoadhesiva'
, 'slug' => str_slug( 'Cintas de PP Autoadhesiva'
), 'subrubro_id' =>  47  ]);App\Category::create(['name' =>  'Copas Invectadas BOYANO-MONALLI'
, 'slug' => str_slug( 'Copas Invectadas BOYANO-MONALLI'
), 'subrubro_id' =>  48  ]);App\Category::create(['name' =>  'Escarbadientes y Palitos de Madera'
, 'slug' => str_slug( 'Escarbadientes y Palitos de Madera'
), 'subrubro_id' =>  49  ]);App\Category::create(['name' =>  'Moldes de Papel'
, 'slug' => str_slug( 'Moldes de Papel'
), 'subrubro_id' =>  50  ]);App\Category::create(['name' =>  'Numeros de Turno y Vales Cantina'
, 'slug' => str_slug( 'Numeros de Turno y Vales Cantina'
), 'subrubro_id' =>  51  ]);App\Category::create(['name' =>  'Papel en Resma Flex-Imp'
, 'slug' => str_slug( 'Papel en Resma Flex-Imp'
), 'subrubro_id' =>  52  ]);App\Category::create(['name' =>  'Precintos para Bolsas'
, 'slug' => str_slug( 'Precintos para Bolsas'
), 'subrubro_id' =>  53  ]);App\Category::create(['name' =>  'Sobres de Papel Pel'
, 'slug' => str_slug( 'Sobres de Papel Pel'
), 'subrubro_id' =>  54  ]);App\Category::create(['name' =>  'Rollos de Papel Obra'
, 'slug' => str_slug( 'Rollos de Papel Obra'
), 'subrubro_id' =>  55  ]);App\Category::create(['name' =>  'Sorbetes'
, 'slug' => str_slug( 'Sorbetes'
), 'subrubro_id' =>  56  ]);App\Category::create(['name' =>  'Bolsas de Consorcio y Residuo ECO'
, 'slug' => str_slug( 'Bolsas de Consorcio y Residuo ECO'
), 'subrubro_id' =>  57  ]);App\Category::create(['name' =>  'Chocolatines'
, 'slug' => str_slug( 'Chocolatines'
), 'subrubro_id' =>  58  ]);App\Category::create(['name' =>  'Galletitas'
, 'slug' => str_slug( 'Galletitas'
), 'subrubro_id' =>  59  ]);App\Category::create(['name' =>  'Heladitos'
, 'slug' => str_slug( 'Heladitos'
), 'subrubro_id' =>  60  ]);App\Category::create(['name' =>  'Chupetines'
, 'slug' => str_slug( 'Chupetines'
), 'subrubro_id' =>  61  ]);App\Category::create(['name' =>  'Merengues'
, 'slug' => str_slug( 'Merengues'
), 'subrubro_id' =>  62  ]);App\Category::create(['name' =>  'Caramelos'
, 'slug' => str_slug( 'Caramelos'
), 'subrubro_id' =>  63  ]);App\Category::create(['name' =>  'Bocaditos Chocolate'
, 'slug' => str_slug( 'Bocaditos Chocolate'
), 'subrubro_id' =>  64  ]);App\Category::create(['name' =>  'Alfajores'
, 'slug' => str_slug( 'Alfajores'
), 'subrubro_id' =>  65  ]);App\Category::create(['name' =>  'Bizcochuelos ARGENSWEET'
, 'slug' => str_slug( 'Bizcochuelos ARGENSWEET'
), 'subrubro_id' =>  66  ]);App\Category::create(['name' =>  'Bolsas Riñon Envadec'
, 'slug' => str_slug( 'Bolsas Riñon Envadec'
), 'subrubro_id' =>  67  ]);App\Category::create(['name' =>  'Papel'
, 'slug' => str_slug( 'Papel'
), 'subrubro_id' =>  68  ]);App\Category::create(['name' =>  'Confites Figuras'
, 'slug' => str_slug( 'Confites Figuras'
), 'subrubro_id' =>  69  ]);App\Category::create(['name' =>  'Jugos de Fruta'
, 'slug' => str_slug( 'Jugos de Fruta'
), 'subrubro_id' =>  70  ]);App\Category::create(['name' =>  'Vasos Termicos DART'
, 'slug' => str_slug( 'Vasos Termicos DART'
), 'subrubro_id' =>  71  ]);App\Category::create(['name' =>  'Laminas para Fiambre'
, 'slug' => str_slug( 'Laminas para Fiambre'
), 'subrubro_id' =>  72  ]);App\Category::create(['name' =>  'Potes Plasticos'
, 'slug' => str_slug( 'Potes Plasticos'
), 'subrubro_id' =>  73  ]);App\Category::create(['name' =>  'Azucar Implapable'
, 'slug' => str_slug( 'Azucar Implapable'
), 'subrubro_id' =>  74  ]);App\Category::create(['name' =>  'Coco Rallado'
, 'slug' => str_slug( 'Coco Rallado'
), 'subrubro_id' =>  75  ]);App\Category::create(['name' =>  'Fecula de Maiz'
, 'slug' => str_slug( 'Fecula de Maiz'
), 'subrubro_id' =>  76  ]);App\Category::create(['name' =>  'Crocante de Mani'
, 'slug' => str_slug( 'Crocante de Mani'
), 'subrubro_id' =>  77  ]);App\Category::create(['name' =>  'Mani Fileteado'
, 'slug' => str_slug( 'Mani Fileteado'
), 'subrubro_id' =>  78  ]);App\Category::create(['name' =>  'Cacao Amargo'
, 'slug' => str_slug( 'Cacao Amargo'
), 'subrubro_id' =>  79  ]);App\Category::create(['name' =>  'Polvo para Hornear'
, 'slug' => str_slug( 'Polvo para Hornear'
), 'subrubro_id' =>  80  ]);App\Category::create(['name' =>  'Mousse'
, 'slug' => str_slug( 'Mousse'
), 'subrubro_id' =>  81  ]);App\Category::create(['name' =>  'Cremor Tartaro'
, 'slug' => str_slug( 'Cremor Tartaro'
), 'subrubro_id' =>  82  ]);App\Category::create(['name' =>  'Confites'
, 'slug' => str_slug( 'Confites'
), 'subrubro_id' =>  83  ]);App\Category::create(['name' =>  'Pastas de Relleno'
, 'slug' => str_slug( 'Pastas de Relleno'
), 'subrubro_id' =>  84  ]);App\Category::create(['name' =>  'Colorantes en Pasta'
, 'slug' => str_slug( 'Colorantes en Pasta'
), 'subrubro_id' =>  85  ]);App\Category::create(['name' =>  'Granas'
, 'slug' => str_slug( 'Granas'
), 'subrubro_id' =>  86  ]);App\Category::create(['name' =>  'Chocolates'
, 'slug' => str_slug( 'Chocolates'
), 'subrubro_id' =>  87  ]);App\Category::create(['name' =>  'Conos de Oblea'
, 'slug' => str_slug( 'Conos de Oblea'
), 'subrubro_id' =>  88  ]);App\Category::create(['name' =>  'Potes Termicos p/Helado'
, 'slug' => str_slug( 'Potes Termicos p/Helado'
), 'subrubro_id' =>  89  ]);App\Category::create(['name' =>  'Cucharas y Paletas de Helado'
, 'slug' => str_slug( 'Cucharas y Paletas de Helado'
), 'subrubro_id' =>  90  ]);App\Category::create(['name' =>  'Velas'
, 'slug' => str_slug( 'Velas'
), 'subrubro_id' =>  91  ]);App\Category::create(['name' =>  'Pirotines'
, 'slug' => str_slug( 'Pirotines'
), 'subrubro_id' =>  92  ]);App\Category::create(['name' =>  'Palitos para Chupetin'
, 'slug' => str_slug( 'Palitos para Chupetin'
), 'subrubro_id' =>  93  ]);App\Category::create(['name' =>  'Esencias'
, 'slug' => str_slug( 'Esencias'
), 'subrubro_id' =>  94  ]);App\Category::create(['name' =>  'Crema Chantilly'
, 'slug' => str_slug( 'Crema Chantilly'
), 'subrubro_id' =>  95  ]);App\Category::create(['name' =>  'Crema Pastelera'
, 'slug' => str_slug( 'Crema Pastelera'
), 'subrubro_id' =>  96  ]);App\Category::create(['name' =>  'Pastas para Cubrir Torta'
, 'slug' => str_slug( 'Pastas para Cubrir Torta'
), 'subrubro_id' =>  97  ]);App\Category::create(['name' =>  'Frutos Secos'
, 'slug' => str_slug( 'Frutos Secos'
), 'subrubro_id' =>  98  ]);App\Category::create(['name' =>  'Pasas de Uva'
, 'slug' => str_slug( 'Pasas de Uva'
), 'subrubro_id' =>  99  ]);App\Category::create(['name' =>  'Bandejas Doradas de Carton WyC'
, 'slug' => str_slug( 'Bandejas Doradas de Carton WyC'
), 'subrubro_id' =>  100  ]);App\Category::create(['name' =>  'Bengalas'
, 'slug' => str_slug( 'Bengalas'
), 'subrubro_id' =>  101  ]);App\Category::create(['name' =>  'Bolsas de Consorcio y Residuo ImprePast'
, 'slug' => str_slug( 'Bolsas de Consorcio y Residuo ImprePast'
), 'subrubro_id' =>  102  ]);App\Category::create(['name' =>  'Bolsas con Cierre Zipper'
, 'slug' => str_slug( 'Bolsas con Cierre Zipper'
), 'subrubro_id' =>  103  ]);App\Category::create(['name' =>  'Bolsas para Horno'
, 'slug' => str_slug( 'Bolsas para Horno'
), 'subrubro_id' =>  104  ]);App\Category::create(['name' =>  'Bolsas de Jugo'
, 'slug' => str_slug( 'Bolsas de Jugo'
), 'subrubro_id' =>  105  ]);App\Category::create(['name' =>  'Bolsas Lechoneras'
, 'slug' => str_slug( 'Bolsas Lechoneras'
), 'subrubro_id' =>  106  ]);App\Category::create(['name' =>  'Bolsas de Farmacia'
, 'slug' => str_slug( 'Bolsas de Farmacia'
), 'subrubro_id' =>  107  ]);App\Category::create(['name' =>  'Bolsas de Arranque en Rollo BD'
, 'slug' => str_slug( 'Bolsas de Arranque en Rollo BD'
), 'subrubro_id' =>  108  ]);App\Category::create(['name' =>  'Bolsas de CD con Solapa'
, 'slug' => str_slug( 'Bolsas de CD con Solapa'
), 'subrubro_id' =>  109  ]);App\Category::create(['name' =>  'Manteles Plasticos'
, 'slug' => str_slug( 'Manteles Plasticos'
), 'subrubro_id' =>  110  ]);App\Category::create(['name' =>  'Bandas Elasticas'
, 'slug' => str_slug( 'Bandas Elasticas'
), 'subrubro_id' =>  111  ]);App\Category::create(['name' =>  'Bandejas de Carton Blancas'
, 'slug' => str_slug( 'Bandejas de Carton Blancas'
), 'subrubro_id' =>  112  ]);App\Category::create(['name' =>  'Conos de Papa de Carton'
, 'slug' => str_slug( 'Conos de Papa de Carton'
), 'subrubro_id' =>  113  ]);App\Category::create(['name' =>  'Fajas de Nombres'
, 'slug' => str_slug( 'Fajas de Nombres'
), 'subrubro_id' =>  114  ]);App\Category::create(['name' =>  'Potes Plasticos p/Helado'
, 'slug' => str_slug( 'Potes Plasticos p/Helado'
), 'subrubro_id' =>  115  ]);App\Category::create(['name' =>  'Salsas p/Helado CORAL'
, 'slug' => str_slug( 'Salsas p/Helado CORAL'
), 'subrubro_id' =>  116  ]);App\Category::create(['name' =>  'Tarjetas de Invitacion'
, 'slug' => str_slug( 'Tarjetas de Invitacion'
), 'subrubro_id' =>  117  ]);App\Category::create(['name' =>  'Bosas para Sorpresitas'
, 'slug' => str_slug( 'Bosas para Sorpresitas'
), 'subrubro_id' =>  118  ]);App\Category::create(['name' =>  'Carteles de Feliz Cupleaños'
, 'slug' => str_slug( 'Carteles de Feliz Cupleaños'
), 'subrubro_id' =>  119  ]);App\Category::create(['name' =>  'Cajas para Armar'
, 'slug' => str_slug( 'Cajas para Armar'
), 'subrubro_id' =>  120  ]);App\Category::create(['name' =>  'Bolsas de Carton Fantasia RomiPack'
, 'slug' => str_slug( 'Bolsas de Carton Fantasia RomiPack'
), 'subrubro_id' =>  121  ]);App\Category::create(['name' =>  'Bandejas Micro Extersa'
, 'slug' => str_slug( 'Bandejas Micro Extersa'
), 'subrubro_id' =>  122  ]);App\Category::create(['name' =>  'Piononos Bon Mase'
, 'slug' => str_slug( 'Piononos Bon Mase'
), 'subrubro_id' =>  123  ]);App\Category::create(['name' =>  'Piñatas de Carton'
, 'slug' => str_slug( 'Piñatas de Carton'
), 'subrubro_id' =>  124  ]);App\Category::create(['name' =>  'Piñatas de Globo'
, 'slug' => str_slug( 'Piñatas de Globo'
), 'subrubro_id' =>  125  ]);App\Category::create(['name' =>  'Gel de Brillo'
, 'slug' => str_slug( 'Gel de Brillo'
), 'subrubro_id' =>  126  ]);App\Category::create(['name' =>  'Bolsas Emblocadas Polimundi'
, 'slug' => str_slug( 'Bolsas Emblocadas Polimundi'
), 'subrubro_id' =>  127  ]);App\Category::create(['name' =>  'Bolsas de Consorcio y Residuo Polimundi'
, 'slug' => str_slug( 'Bolsas de Consorcio y Residuo Polimundi'
), 'subrubro_id' =>  128  ]);App\Category::create(['name' =>  'Globos'
, 'slug' => str_slug( 'Globos'
), 'subrubro_id' =>  129  ]);App\Category::create(['name' =>  'Placas para Modelar'
, 'slug' => str_slug( 'Placas para Modelar'
), 'subrubro_id' =>  130  ]);App\Category::create(['name' =>  'Placas Comestible'
, 'slug' => str_slug( 'Placas Comestible'
), 'subrubro_id' =>  131  ]);App\Category::create(['name' =>  'Guantes Descartables'
, 'slug' => str_slug( 'Guantes Descartables'
), 'subrubro_id' =>  132  ]);App\Category::create(['name' =>  'Cuñetes'
, 'slug' => str_slug( 'Cuñetes'
), 'subrubro_id' =>  133  ]);App\Category::create(['name' =>  'Mangas Descartables'
, 'slug' => str_slug( 'Mangas Descartables'
), 'subrubro_id' =>  134  ]);App\Category::create(['name' =>  'Rollos de Aluminio'
, 'slug' => str_slug( 'Rollos de Aluminio'
), 'subrubro_id' =>  135  ]);App\Category::create(['name' =>  'Dulce de Leche'
, 'slug' => str_slug( 'Dulce de Leche'
), 'subrubro_id' =>  136  ]);App\Category::create(['name' =>  'Bandejas Plasticas Work'
, 'slug' => str_slug( 'Bandejas Plasticas Work'
), 'subrubro_id' =>  137  ]);App\Category::create(['name' =>  'Stickers'
, 'slug' => str_slug( 'Stickers'
), 'subrubro_id' =>  138  ]);App\Category::create(['name' =>  'Velas Plasticas'
, 'slug' => str_slug( 'Velas Plasticas'
), 'subrubro_id' =>  139  ]);App\Category::create(['name' =>  'Cajitas de Carton'
, 'slug' => str_slug( 'Cajitas de Carton'
), 'subrubro_id' =>  140  ]);App\Category::create(['name' =>  'Fundas de Traje'
, 'slug' => str_slug( 'Fundas de Traje'
), 'subrubro_id' =>  141  ]);App\Category::create(['name' =>  'Cartones de Bingo'
, 'slug' => str_slug( 'Cartones de Bingo'
), 'subrubro_id' =>  142  ]);App\Category::create(['name' =>  'Palitos para Globo'
, 'slug' => str_slug( 'Palitos para Globo'
), 'subrubro_id' =>  143  ]);App\Category::create(['name' =>  'Bolsas Camisetas BD'
, 'slug' => str_slug( 'Bolsas Camisetas BD'
), 'subrubro_id' =>  144  ]);App\Category::create(['name' =>  'Papel Fantasia en Rollo'
, 'slug' => str_slug( 'Papel Fantasia en Rollo'
), 'subrubro_id' =>  145  ]);App\Category::create(['name' =>  'Papel Manteca'
, 'slug' => str_slug( 'Papel Manteca'
), 'subrubro_id' =>  146  ]);App\Category::create(['name' =>  'Papel en Resma MAG'
, 'slug' => str_slug( 'Papel en Resma MAG'
), 'subrubro_id' =>  147  ]);App\Category::create(['name' =>  'Papel en Resma Metalizado'
, 'slug' => str_slug( 'Papel en Resma Metalizado'
), 'subrubro_id' =>  148  ]);App\Category::create(['name' =>  'Boquillas para Reposteria'
, 'slug' => str_slug( 'Boquillas para Reposteria'
), 'subrubro_id' =>  149  ]);App\Category::create(['name' =>  'Fajas de Carton'
, 'slug' => str_slug( 'Fajas de Carton'
), 'subrubro_id' =>  150  ]);App\Category::create(['name' =>  'Bolsas Holograficas'
, 'slug' => str_slug( 'Bolsas Holograficas'
), 'subrubro_id' =>  151  ]);App\Category::create(['name' =>  'Sobres con Lunares'
, 'slug' => str_slug( 'Sobres con Lunares'
), 'subrubro_id' =>  152  ]);App\Category::create(['name' =>  'Bolsas Camisetas Impresas Marca'
, 'slug' => str_slug( 'Bolsas Camisetas Impresas Marca'
), 'subrubro_id' =>  153  ]);App\Category::create(['name' =>  'Sobres de Papel Movar'
, 'slug' => str_slug( 'Sobres de Papel Movar'
), 'subrubro_id' =>  154  ]);App\Category::create(['name' =>  'Cajas de Regalo c/Moño'
, 'slug' => str_slug( 'Cajas de Regalo c/Moño'
), 'subrubro_id' =>  155  ]);App\Category::create(['name' =>  'Conos de Oblea y Cucuruchos'
, 'slug' => str_slug( 'Conos de Oblea y Cucuruchos'
), 'subrubro_id' =>  156  ]);App\Category::create(['name' =>  'Cartelitos para Precio'
, 'slug' => str_slug( 'Cartelitos para Precio'
), 'subrubro_id' =>  157  ]);App\Category::create(['name' =>  'Porta Cintas'
, 'slug' => str_slug( 'Porta Cintas'
), 'subrubro_id' =>  158  ]);App\Category::create(['name' =>  'Calculadoras'
, 'slug' => str_slug( 'Calculadoras'
), 'subrubro_id' =>  159  ]);App\Category::create(['name' =>  'Mangas Soldadas'
, 'slug' => str_slug( 'Mangas Soldadas'
), 'subrubro_id' =>  160  ]);App\Category::create(['name' =>  'Salsa p/Helado EUREKA'
, 'slug' => str_slug( 'Salsa p/Helado EUREKA'
), 'subrubro_id' =>  161  ]);App\Category::create(['name' =>  'Moldes de Chapa'
, 'slug' => str_slug( 'Moldes de Chapa'
), 'subrubro_id' =>  162  ]);App\Category::create(['name' =>  'Bolsas de Pan Rallado'
, 'slug' => str_slug( 'Bolsas de Pan Rallado'
), 'subrubro_id' =>  163  ]);App\Category::create(['name' =>  'Pinzas'
, 'slug' => str_slug( 'Pinzas'
), 'subrubro_id' =>  164  ]);App\Category::create(['name' =>  'Manteles Individuales'
, 'slug' => str_slug( 'Manteles Individuales'
), 'subrubro_id' =>  165  ]);App\Category::create(['name' =>  'Torteras'
, 'slug' => str_slug( 'Torteras'
), 'subrubro_id' =>  166  ]);App\Category::create(['name' =>  'Papel Higienico'
, 'slug' => str_slug( 'Papel Higienico'
), 'subrubro_id' =>  167  ]);App\Category::create(['name' =>  'Carteles Alto Impacto'
, 'slug' => str_slug( 'Carteles Alto Impacto'
), 'subrubro_id' =>  168  ]);App\Category::create(['name' =>  'Moldes para Bizcochuelo'
, 'slug' => str_slug( 'Moldes para Bizcochuelo'
), 'subrubro_id' =>  169  ]);App\Category::create(['name' =>  'Moldes para Pan Dulce'
, 'slug' => str_slug( 'Moldes para Pan Dulce'
), 'subrubro_id' =>  170  ]);App\Category::create(['name' =>  'Sobres Holograficos'
, 'slug' => str_slug( 'Sobres Holograficos'
), 'subrubro_id' =>  171  ]);App\Category::create(['name' =>  'Juguetitos'
, 'slug' => str_slug( 'Juguetitos'
), 'subrubro_id' =>  172  ]);App\Category::create(['name' =>  'Cajas Navideñas'
, 'slug' => str_slug( 'Cajas Navideñas'
), 'subrubro_id' =>  173  ]);App\Category::create(['name' =>  'Bandejas Micro Cotnyl'
, 'slug' => str_slug( 'Bandejas Micro Cotnyl'
), 'subrubro_id' =>  174  ]);App\Category::create(['name' =>  'Papel Ajmechet'
, 'slug' => str_slug( 'Papel Ajmechet'
), 'subrubro_id' =>  175  ]);App\Category::create(['name' =>  'Fruta Escurrida'
, 'slug' => str_slug( 'Fruta Escurrida'
), 'subrubro_id' =>  176  ]);App\Category::create(['name' =>  'Espuma en Aerosol'
, 'slug' => str_slug( 'Espuma en Aerosol'
), 'subrubro_id' =>  177  ]);App\Category::create(['name' =>  'Pinturas'
, 'slug' => str_slug( 'Pinturas'
), 'subrubro_id' =>  178  ]);App\Category::create(['name' =>  'Serpentina en Aerosol'
, 'slug' => str_slug( 'Serpentina en Aerosol'
), 'subrubro_id' =>  179  ]);App\Category::create(['name' =>  'Tarteletas'
, 'slug' => str_slug( 'Tarteletas'
), 'subrubro_id' =>  180  ]);App\Category::create(['name' =>  'Tijeras'
, 'slug' => str_slug( 'Tijeras'
), 'subrubro_id' =>  181  ]);App\Category::create(['name' =>  'Abrochadoras'
, 'slug' => str_slug( 'Abrochadoras'
), 'subrubro_id' =>  182  ]);App\Category::create(['name' =>  'Cajas de Ravioles'
, 'slug' => str_slug( 'Cajas de Ravioles'
), 'subrubro_id' =>  183  ]);App\Category::create(['name' =>  'Moldes para Huevos'
, 'slug' => str_slug( 'Moldes para Huevos'
), 'subrubro_id' =>  184  ]);App\Category::create(['name' =>  'Bases para Huevo'
, 'slug' => str_slug( 'Bases para Huevo'
), 'subrubro_id' =>  185  ]);App\Category::create(['name' =>  'Glace'
, 'slug' => str_slug( 'Glace'
), 'subrubro_id' =>  186  ]);App\Category::create(['name' =>  'Flores y Figuras Pascua'
, 'slug' => str_slug( 'Flores y Figuras Pascua'
), 'subrubro_id' =>  187  ]);App\Category::create(['name' =>  'Moldes para Rosca'
, 'slug' => str_slug( 'Moldes para Rosca'
), 'subrubro_id' =>  188  ]);App\Category::create(['name' =>  'Clips'
, 'slug' => str_slug( 'Clips'
), 'subrubro_id' =>  189  ]);App\Category::create(['name' =>  'Mojadedo '
, 'slug' => str_slug( 'Mojadedo '
), 'subrubro_id' =>  190  ]);App\Category::create(['name' =>  'Tacos de Color'
, 'slug' => str_slug( 'Tacos de Color'
), 'subrubro_id' =>  191  ]);App\Category::create(['name' =>  'Cutters'
, 'slug' => str_slug( 'Cutters'
), 'subrubro_id' =>  192  ]);App\Category::create(['name' =>  'Colorantes Liquidos'
, 'slug' => str_slug( 'Colorantes Liquidos'
), 'subrubro_id' =>  193  ]);App\Category::create(['name' =>  'Porta Panchos'
, 'slug' => str_slug( 'Porta Panchos'
), 'subrubro_id' =>  194  ]);App\Category::create(['name' =>  'Glucosa'
, 'slug' => str_slug( 'Glucosa'
), 'subrubro_id' =>  195  ]);App\Category::create(['name' =>  'Porcelana Fria'
, 'slug' => str_slug( 'Porcelana Fria'
), 'subrubro_id' =>  196  ]);App\Category::create(['name' =>  'Pastillaje'
, 'slug' => str_slug( 'Pastillaje'
), 'subrubro_id' =>  197  ]);App\Category::create(['name' =>  'Pasta de Goma'
, 'slug' => str_slug( 'Pasta de Goma'
), 'subrubro_id' =>  198  ]);App\Category::create(['name' =>  'Polvo Pre Mezcla'
, 'slug' => str_slug( 'Polvo Pre Mezcla'
), 'subrubro_id' =>  199  ]);App\Category::create(['name' =>  'Porta Muffins'
, 'slug' => str_slug( 'Porta Muffins'
), 'subrubro_id' =>  200  ]);App\Category::create(['name' =>  'Bandejas de Carton Gris'
, 'slug' => str_slug( 'Bandejas de Carton Gris'
), 'subrubro_id' =>  201  ]);App\Category::create(['name' =>  'Bolsas de Consorcio SUPER CONSORCIO'
, 'slug' => str_slug( 'Bolsas de Consorcio SUPER CONSORCIO'
), 'subrubro_id' =>  202  ]);App\Category::create(['name' =>  'Ensaladera'
, 'slug' => str_slug( 'Ensaladera'
), 'subrubro_id' =>  203  ]);App\Category::create(['name' =>  'Bolsas Emblocadas SUPOL'
, 'slug' => str_slug( 'Bolsas Emblocadas SUPOL'
), 'subrubro_id' =>  204  ]);App\Category::create(['name' =>  'Guirnaldas'
, 'slug' => str_slug( 'Guirnaldas'
), 'subrubro_id' =>  205  ]);App\Category::create(['name' =>  'Mani Saborizado'
, 'slug' => str_slug( 'Mani Saborizado'
), 'subrubro_id' =>  206  ]);App\Category::create(['name' =>  'Pasta para Modelar'
, 'slug' => str_slug( 'Pasta para Modelar'
), 'subrubro_id' =>  207  ]);App\Category::create(['name' =>  'Papel Picado'
, 'slug' => str_slug( 'Papel Picado'
), 'subrubro_id' =>  208  ]);App\Category::create(['name' =>  'Bandejas Doradas KP'
, 'slug' => str_slug( 'Bandejas Doradas KP'
), 'subrubro_id' =>  209  ]);App\Category::create(['name' =>  'Inflador de Globos'
, 'slug' => str_slug( 'Inflador de Globos'
), 'subrubro_id' =>  210  ]);App\Category::create(['name' =>  'Dulces'
, 'slug' => str_slug( 'Dulces'
), 'subrubro_id' =>  211  ]);App\Category::create(['name' =>  'Bizcochuelos Mil Keiks'
, 'slug' => str_slug( 'Bizcochuelos Mil Keiks'
), 'subrubro_id' =>  212  ]);App\Category::create(['name' =>  'Bizcochuelos Lyvian'
, 'slug' => str_slug( 'Bizcochuelos Lyvian'
), 'subrubro_id' =>  213  ]);App\Category::create(['name' =>  'Lapiz Tinta Comestible'
, 'slug' => str_slug( 'Lapiz Tinta Comestible'
), 'subrubro_id' =>  214  ]);App\Category::create(['name' =>  'Cubanitos'
, 'slug' => str_slug( 'Cubanitos'
), 'subrubro_id' =>  215  ]);App\Category::create(['name' =>  'Extracto de Malta'
, 'slug' => str_slug( 'Extracto de Malta'
), 'subrubro_id' =>  216  ]);App\Category::create(['name' =>  'Rollos Quimicos'
, 'slug' => str_slug( 'Rollos Quimicos'
), 'subrubro_id' =>  217  ]);App\Category::create(['name' =>  'Sobres de Papel KP'
, 'slug' => str_slug( 'Sobres de Papel KP'
), 'subrubro_id' =>  218  ]);App\Category::create(['name' =>  'Rollos de Papel Termico'
, 'slug' => str_slug( 'Rollos de Papel Termico'
), 'subrubro_id' =>  219  ]);App\Category::create(['name' =>  'Etiquetas Balanza'
, 'slug' => str_slug( 'Etiquetas Balanza'
), 'subrubro_id' =>  220  ]);App\Category::create(['name' =>  'Bizcochuelos NATALIA'
, 'slug' => str_slug( 'Bizcochuelos NATALIA'
), 'subrubro_id' =>  221  ]);App\Category::create(['name' =>  'Cinta Impresora'
, 'slug' => str_slug( 'Cinta Impresora'
), 'subrubro_id' =>  222  ]);App\Category::create(['name' =>  'Obleas'
, 'slug' => str_slug( 'Obleas'
), 'subrubro_id' =>  223  ]);App\Category::create(['name' =>  'Cerezas en Almibar'
, 'slug' => str_slug( 'Cerezas en Almibar'
), 'subrubro_id' =>  224  ]);App\Category::create(['name' =>  'Cortantes para Masa'
, 'slug' => str_slug( 'Cortantes para Masa'
), 'subrubro_id' =>  225  ]);App\Category::create(['name' =>  'Adhesivo Comestible'
, 'slug' => str_slug( 'Adhesivo Comestible'
), 'subrubro_id' =>  226  ]);App\Category::create(['name' =>  'Gelatina sin Sabor'
, 'slug' => str_slug( 'Gelatina sin Sabor'
), 'subrubro_id' =>  227  ]);App\Category::create(['name' =>  'Bowl'
, 'slug' => str_slug( 'Bowl'
), 'subrubro_id' =>  228  ]);App\Category::create(['name' =>  'Duraznos'
, 'slug' => str_slug( 'Duraznos'
), 'subrubro_id' =>  229  ]);App\Category::create(['name' =>  'Bandejas Plasticas BANDEX'
, 'slug' => str_slug( 'Bandejas Plasticas BANDEX'
), 'subrubro_id' =>  230  ]);App\Category::create(['name' =>  'Bolsas de Carton Murillo'
, 'slug' => str_slug( 'Bolsas de Carton Murillo'
), 'subrubro_id' =>  231  ]);App\Category::create(['name' =>  'Humectante para torta'
, 'slug' => str_slug( 'Humectante para torta'
), 'subrubro_id' =>  232  ]);App\Category::create(['name' =>  'Papel para Bombones'
, 'slug' => str_slug( 'Papel para Bombones'
), 'subrubro_id' =>  233  ]);App\Category::create(['name' =>  'Bolsas Riñon IMPORT'
, 'slug' => str_slug( 'Bolsas Riñon IMPORT'
), 'subrubro_id' =>  234  ]);App\Category::create(['name' =>  'Bandejas Plasticas Bisagra PFOOD'
, 'slug' => str_slug( 'Bandejas Plasticas Bisagra PFOOD'
), 'subrubro_id' =>  235  ]);App\Category::create(['name' =>  'Mani con Chocolate'
, 'slug' => str_slug( 'Mani con Chocolate'
), 'subrubro_id' =>  236  ]);App\Category::create(['name' =>  'Bolsas de Carton Fantasia EVACOR'
, 'slug' => str_slug( 'Bolsas de Carton Fantasia EVACOR'
), 'subrubro_id' =>  237  ]);App\Category::create(['name' =>  'Clavos para Hacer Flores'
, 'slug' => str_slug( 'Clavos para Hacer Flores'
), 'subrubro_id' =>  238  ]);App\Category::create(['name' =>  'Estecas'
, 'slug' => str_slug( 'Estecas'
), 'subrubro_id' =>  239  ]);App\Category::create(['name' =>  'Palos para Amasar'
, 'slug' => str_slug( 'Palos para Amasar'
), 'subrubro_id' =>  240  ]);App\Category::create(['name' =>  'Posatorta'
, 'slug' => str_slug( 'Posatorta'
), 'subrubro_id' =>  241  ]);App\Category::create(['name' =>  'Espatulas para Reposteria'
, 'slug' => str_slug( 'Espatulas para Reposteria'
), 'subrubro_id' =>  242  ]);App\Category::create(['name' =>  'Vaso Medidor'
, 'slug' => str_slug( 'Vaso Medidor'
), 'subrubro_id' =>  243  ]);App\Category::create(['name' =>  'Moldes de Aluminio'
, 'slug' => str_slug( 'Moldes de Aluminio'
), 'subrubro_id' =>  244  ]);App\Category::create(['name' =>  'Decoracion NAVIDAD'
, 'slug' => str_slug( 'Decoracion NAVIDAD'
), 'subrubro_id' =>  245  ]);App\Category::create(['name' =>  'Set de Churros'
, 'slug' => str_slug( 'Set de Churros'
), 'subrubro_id' =>  246  ]);App\Category::create(['name' =>  'Colorantes Liposolubles'
, 'slug' => str_slug( 'Colorantes Liposolubles'
), 'subrubro_id' =>  247  ]);App\Category::create(['name' =>  'Fratachos'
, 'slug' => str_slug( 'Fratachos'
), 'subrubro_id' =>  248  ]);App\Category::create(['name' =>  'Cajas para Huevo'
, 'slug' => str_slug( 'Cajas para Huevo'
), 'subrubro_id' =>  249  ]);App\Category::create(['name' =>  'Lentejas de Chocolate'
, 'slug' => str_slug( 'Lentejas de Chocolate'
), 'subrubro_id' =>  250  ]);App\Category::create(['name' =>  'Bolsas de Arranque en Rollo RENDIDOR'
, 'slug' => str_slug( 'Bolsas de Arranque en Rollo RENDIDOR'
), 'subrubro_id' =>  251  ]);
    }
}
