<?php

use Illuminate\Database\Seeder;

class SubrubrosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Subrubro::create(['name' =>  'Bolsas Emblocadas MAPA'
, 'slug' => str_slug( 'Bolsas Emblocadas MAPA'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas en Rollo BD MAPA'
, 'slug' => str_slug( 'Bolsas en Rollo BD MAPA'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Consorcio BARPLAST'
, 'slug' => str_slug( 'Bolsas de Consorcio BARPLAST'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Polietileno con Burbujas'
, 'slug' => str_slug( 'Polietileno con Burbujas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Tripodes para Pizzas'
, 'slug' => str_slug( 'Tripodes para Pizzas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Film Stretch'
, 'slug' => str_slug( 'Film Stretch'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Hilos'
, 'slug' => str_slug( 'Hilos'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cubiertos Plasticos'
, 'slug' => str_slug( 'Cubiertos Plasticos'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Vasos Plasticos'
, 'slug' => str_slug( 'Vasos Plasticos'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Film de PVC'
, 'slug' => str_slug( 'Film de PVC'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel Muresco'
, 'slug' => str_slug( 'Papel Muresco'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel Murillo'
, 'slug' => str_slug( 'Papel Murillo'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Porta Bobinas de Papel'
, 'slug' => str_slug( 'Porta Bobinas de Papel'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Servilletas de Papel'
, 'slug' => str_slug( 'Servilletas de Papel'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Sobres de Papel Muresco'
, 'slug' => str_slug( 'Sobres de Papel Muresco'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas Doradas Configraf'
, 'slug' => str_slug( 'Bandejas Doradas Configraf'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Vasos Plasticos Trago Largo'
, 'slug' => str_slug( 'Vasos Plasticos Trago Largo'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Platos Plasticos'
, 'slug' => str_slug( 'Platos Plasticos'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Plastiflechas'
, 'slug' => str_slug( 'Plastiflechas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cintas de Regalo'
, 'slug' => str_slug( 'Cintas de Regalo'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Moños'
, 'slug' => str_slug( 'Moños'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas Riñon Terlizzi'
, 'slug' => str_slug( 'Bolsas Riñon Terlizzi'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Libretas'
, 'slug' => str_slug( 'Libretas'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Marcadores'
, 'slug' => str_slug( 'Marcadores'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Chinches'
, 'slug' => str_slug( 'Chinches'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Etiquetas'
, 'slug' => str_slug( 'Etiquetas'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Biromes'
, 'slug' => str_slug( 'Biromes'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Broches'
, 'slug' => str_slug( 'Broches'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Saladitos'
, 'slug' => str_slug( 'Saladitos'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Bolsas Camisetas AD'
, 'slug' => str_slug( 'Bolsas Camisetas AD'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Arranque en Rollo AD'
, 'slug' => str_slug( 'Bolsas de Arranque en Rollo AD'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas Plasticas Arenales'
, 'slug' => str_slug( 'Bandejas Plasticas Arenales'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas Micro CelPack'
, 'slug' => str_slug( 'Bandejas Micro CelPack'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas de Expandido'
, 'slug' => str_slug( 'Bandejas de Expandido'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas Aluminio Alpac'
, 'slug' => str_slug( 'Bandejas Aluminio Alpac'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Blondas de Papel Configraf'
, 'slug' => str_slug( 'Blondas de Papel Configraf'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas con Abrojo y Moño'
, 'slug' => str_slug( 'Bolsas con Abrojo y Moño'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Panaderia Envasadas'
, 'slug' => str_slug( 'Bolsas de Panaderia Envasadas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Polipropileno'
, 'slug' => str_slug( 'Bolsas de Polipropileno'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cajas de Carton Común'
, 'slug' => str_slug( 'Cajas de Carton Común'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cajas de Bombones'
, 'slug' => str_slug( 'Cajas de Bombones'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cajas para Masas'
, 'slug' => str_slug( 'Cajas para Masas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cajas de Pizza Redonda'
, 'slug' => str_slug( 'Cajas de Pizza Redonda'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cajas de Pizza Microcorrugado'
, 'slug' => str_slug( 'Cajas de Pizza Microcorrugado'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Maples para Huevos'
, 'slug' => str_slug( 'Maples para Huevos'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cintas de Papel Autoad. PackTape'
, 'slug' => str_slug( 'Cintas de Papel Autoad. PackTape'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cintas de PP Autoadhesiva'
, 'slug' => str_slug( 'Cintas de PP Autoadhesiva'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Copas Invectadas BOYANO-MONALLI'
, 'slug' => str_slug( 'Copas Invectadas BOYANO-MONALLI'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Escarbadientes y Palitos de Madera'
, 'slug' => str_slug( 'Escarbadientes y Palitos de Madera'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Moldes de Papel'
, 'slug' => str_slug( 'Moldes de Papel'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Numeros de Turno y Vales Cantina'
, 'slug' => str_slug( 'Numeros de Turno y Vales Cantina'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel en Resma Flex-Imp'
, 'slug' => str_slug( 'Papel en Resma Flex-Imp'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Precintos para Bolsas'
, 'slug' => str_slug( 'Precintos para Bolsas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Sobres de Papel Pel'
, 'slug' => str_slug( 'Sobres de Papel Pel'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Rollos de Papel Obra'
, 'slug' => str_slug( 'Rollos de Papel Obra'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Sorbetes'
, 'slug' => str_slug( 'Sorbetes'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Consorcio y Residuo ECO'
, 'slug' => str_slug( 'Bolsas de Consorcio y Residuo ECO'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Chocolatines'
, 'slug' => str_slug( 'Chocolatines'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Galletitas'
, 'slug' => str_slug( 'Galletitas'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Heladitos'
, 'slug' => str_slug( 'Heladitos'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Chupetines'
, 'slug' => str_slug( 'Chupetines'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Merengues'
, 'slug' => str_slug( 'Merengues'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Caramelos'
, 'slug' => str_slug( 'Caramelos'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Bocaditos Chocolate'
, 'slug' => str_slug( 'Bocaditos Chocolate'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Alfajores'
, 'slug' => str_slug( 'Alfajores'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Bizcochuelos ARGENSWEET'
, 'slug' => str_slug( 'Bizcochuelos ARGENSWEET'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bolsas Riñon Envadec'
, 'slug' => str_slug( 'Bolsas Riñon Envadec'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel'
, 'slug' => str_slug( 'Papel'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Confites Figuras'
, 'slug' => str_slug( 'Confites Figuras'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Jugos de Fruta'
, 'slug' => str_slug( 'Jugos de Fruta'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Vasos Termicos DART'
, 'slug' => str_slug( 'Vasos Termicos DART'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Laminas para Fiambre'
, 'slug' => str_slug( 'Laminas para Fiambre'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Potes Plasticos'
, 'slug' => str_slug( 'Potes Plasticos'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Azucar Implapable'
, 'slug' => str_slug( 'Azucar Implapable'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Coco Rallado'
, 'slug' => str_slug( 'Coco Rallado'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Fecula de Maiz'
, 'slug' => str_slug( 'Fecula de Maiz'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Crocante de Mani'
, 'slug' => str_slug( 'Crocante de Mani'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Mani Fileteado'
, 'slug' => str_slug( 'Mani Fileteado'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Cacao Amargo'
, 'slug' => str_slug( 'Cacao Amargo'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Polvo para Hornear'
, 'slug' => str_slug( 'Polvo para Hornear'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Mousse'
, 'slug' => str_slug( 'Mousse'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Cremor Tartaro'
, 'slug' => str_slug( 'Cremor Tartaro'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Confites'
, 'slug' => str_slug( 'Confites'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Pastas de Relleno'
, 'slug' => str_slug( 'Pastas de Relleno'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Colorantes en Pasta'
, 'slug' => str_slug( 'Colorantes en Pasta'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Granas'
, 'slug' => str_slug( 'Granas'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Chocolates'
, 'slug' => str_slug( 'Chocolates'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Conos de Oblea'
, 'slug' => str_slug( 'Conos de Oblea'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Potes Termicos p/Helado'
, 'slug' => str_slug( 'Potes Termicos p/Helado'
), 'rubro_id' => '4' ]);App\Subrubro::create(['name' =>  'Cucharas y Paletas de Helado'
, 'slug' => str_slug( 'Cucharas y Paletas de Helado'
), 'rubro_id' => '4' ]);App\Subrubro::create(['name' =>  'Velas'
, 'slug' => str_slug( 'Velas'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Pirotines'
, 'slug' => str_slug( 'Pirotines'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Palitos para Chupetin'
, 'slug' => str_slug( 'Palitos para Chupetin'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Esencias'
, 'slug' => str_slug( 'Esencias'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Crema Chantilly'
, 'slug' => str_slug( 'Crema Chantilly'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Crema Pastelera'
, 'slug' => str_slug( 'Crema Pastelera'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Pastas para Cubrir Torta'
, 'slug' => str_slug( 'Pastas para Cubrir Torta'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Frutos Secos'
, 'slug' => str_slug( 'Frutos Secos'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Pasas de Uva'
, 'slug' => str_slug( 'Pasas de Uva'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bandejas Doradas de Carton WyC'
, 'slug' => str_slug( 'Bandejas Doradas de Carton WyC'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bengalas'
, 'slug' => str_slug( 'Bengalas'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Bolsas de Consorcio y Residuo ImprePast'
, 'slug' => str_slug( 'Bolsas de Consorcio y Residuo ImprePast'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas con Cierre Zipper'
, 'slug' => str_slug( 'Bolsas con Cierre Zipper'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas para Horno'
, 'slug' => str_slug( 'Bolsas para Horno'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Jugo'
, 'slug' => str_slug( 'Bolsas de Jugo'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas Lechoneras'
, 'slug' => str_slug( 'Bolsas Lechoneras'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Farmacia'
, 'slug' => str_slug( 'Bolsas de Farmacia'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Arranque en Rollo BD'
, 'slug' => str_slug( 'Bolsas de Arranque en Rollo BD'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de CD con Solapa'
, 'slug' => str_slug( 'Bolsas de CD con Solapa'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Manteles Plasticos'
, 'slug' => str_slug( 'Manteles Plasticos'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Bandas Elasticas'
, 'slug' => str_slug( 'Bandas Elasticas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas de Carton Blancas'
, 'slug' => str_slug( 'Bandejas de Carton Blancas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Conos de Papa de Carton'
, 'slug' => str_slug( 'Conos de Papa de Carton'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Fajas de Nombres'
, 'slug' => str_slug( 'Fajas de Nombres'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Potes Plasticos p/Helado'
, 'slug' => str_slug( 'Potes Plasticos p/Helado'
), 'rubro_id' => '4' ]);App\Subrubro::create(['name' =>  'Salsas p/Helado CORAL'
, 'slug' => str_slug( 'Salsas p/Helado CORAL'
), 'rubro_id' => '4' ]);App\Subrubro::create(['name' =>  'Tarjetas de Invitacion'
, 'slug' => str_slug( 'Tarjetas de Invitacion'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Bosas para Sorpresitas'
, 'slug' => str_slug( 'Bosas para Sorpresitas'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Carteles de Feliz Cupleaños'
, 'slug' => str_slug( 'Carteles de Feliz Cupleaños'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Cajas para Armar'
, 'slug' => str_slug( 'Cajas para Armar'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Bolsas de Carton Fantasia RomiPack'
, 'slug' => str_slug( 'Bolsas de Carton Fantasia RomiPack'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas Micro Extersa'
, 'slug' => str_slug( 'Bandejas Micro Extersa'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Piononos Bon Mase'
, 'slug' => str_slug( 'Piononos Bon Mase'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Piñatas de Carton'
, 'slug' => str_slug( 'Piñatas de Carton'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Piñatas de Globo'
, 'slug' => str_slug( 'Piñatas de Globo'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Gel de Brillo'
, 'slug' => str_slug( 'Gel de Brillo'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bolsas Emblocadas Polimundi'
, 'slug' => str_slug( 'Bolsas Emblocadas Polimundi'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Consorcio y Residuo Polimundi'
, 'slug' => str_slug( 'Bolsas de Consorcio y Residuo Polimundi'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Globos'
, 'slug' => str_slug( 'Globos'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Placas para Modelar'
, 'slug' => str_slug( 'Placas para Modelar'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Placas Comestible'
, 'slug' => str_slug( 'Placas Comestible'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Guantes Descartables'
, 'slug' => str_slug( 'Guantes Descartables'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cuñetes'
, 'slug' => str_slug( 'Cuñetes'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Mangas Descartables'
, 'slug' => str_slug( 'Mangas Descartables'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Rollos de Aluminio'
, 'slug' => str_slug( 'Rollos de Aluminio'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Dulce de Leche'
, 'slug' => str_slug( 'Dulce de Leche'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bandejas Plasticas Work'
, 'slug' => str_slug( 'Bandejas Plasticas Work'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Stickers'
, 'slug' => str_slug( 'Stickers'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Velas Plasticas'
, 'slug' => str_slug( 'Velas Plasticas'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Cajitas de Carton'
, 'slug' => str_slug( 'Cajitas de Carton'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Fundas de Traje'
, 'slug' => str_slug( 'Fundas de Traje'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cartones de Bingo'
, 'slug' => str_slug( 'Cartones de Bingo'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Palitos para Globo'
, 'slug' => str_slug( 'Palitos para Globo'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Bolsas Camisetas BD'
, 'slug' => str_slug( 'Bolsas Camisetas BD'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel Fantasia en Rollo'
, 'slug' => str_slug( 'Papel Fantasia en Rollo'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel Manteca'
, 'slug' => str_slug( 'Papel Manteca'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel en Resma MAG'
, 'slug' => str_slug( 'Papel en Resma MAG'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel en Resma Metalizado'
, 'slug' => str_slug( 'Papel en Resma Metalizado'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Boquillas para Reposteria'
, 'slug' => str_slug( 'Boquillas para Reposteria'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Fajas de Carton'
, 'slug' => str_slug( 'Fajas de Carton'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas Holograficas'
, 'slug' => str_slug( 'Bolsas Holograficas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Sobres con Lunares'
, 'slug' => str_slug( 'Sobres con Lunares'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas Camisetas Impresas Marca'
, 'slug' => str_slug( 'Bolsas Camisetas Impresas Marca'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Sobres de Papel Movar'
, 'slug' => str_slug( 'Sobres de Papel Movar'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Cajas de Regalo c/Moño'
, 'slug' => str_slug( 'Cajas de Regalo c/Moño'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Conos de Oblea y Cucuruchos'
, 'slug' => str_slug( 'Conos de Oblea y Cucuruchos'
), 'rubro_id' => '4' ]);App\Subrubro::create(['name' =>  'Cartelitos para Precio'
, 'slug' => str_slug( 'Cartelitos para Precio'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Porta Cintas'
, 'slug' => str_slug( 'Porta Cintas'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Calculadoras'
, 'slug' => str_slug( 'Calculadoras'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Mangas Soldadas'
, 'slug' => str_slug( 'Mangas Soldadas'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Salsa p/Helado EUREKA'
, 'slug' => str_slug( 'Salsa p/Helado EUREKA'
), 'rubro_id' => '4' ]);App\Subrubro::create(['name' =>  'Moldes de Chapa'
, 'slug' => str_slug( 'Moldes de Chapa'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bolsas de Pan Rallado'
, 'slug' => str_slug( 'Bolsas de Pan Rallado'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Pinzas'
, 'slug' => str_slug( 'Pinzas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Manteles Individuales'
, 'slug' => str_slug( 'Manteles Individuales'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Torteras'
, 'slug' => str_slug( 'Torteras'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel Higienico'
, 'slug' => str_slug( 'Papel Higienico'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Carteles Alto Impacto'
, 'slug' => str_slug( 'Carteles Alto Impacto'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Moldes para Bizcochuelo'
, 'slug' => str_slug( 'Moldes para Bizcochuelo'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Moldes para Pan Dulce'
, 'slug' => str_slug( 'Moldes para Pan Dulce'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Sobres Holograficos'
, 'slug' => str_slug( 'Sobres Holograficos'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Juguetitos'
, 'slug' => str_slug( 'Juguetitos'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Cajas Navideñas'
, 'slug' => str_slug( 'Cajas Navideñas'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas Micro Cotnyl'
, 'slug' => str_slug( 'Bandejas Micro Cotnyl'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Papel Ajmechet'
, 'slug' => str_slug( 'Papel Ajmechet'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Fruta Escurrida'
, 'slug' => str_slug( 'Fruta Escurrida'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Espuma en Aerosol'
, 'slug' => str_slug( 'Espuma en Aerosol'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Pinturas'
, 'slug' => str_slug( 'Pinturas'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Serpentina en Aerosol'
, 'slug' => str_slug( 'Serpentina en Aerosol'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Tarteletas'
, 'slug' => str_slug( 'Tarteletas'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Tijeras'
, 'slug' => str_slug( 'Tijeras'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Abrochadoras'
, 'slug' => str_slug( 'Abrochadoras'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Cajas de Ravioles'
, 'slug' => str_slug( 'Cajas de Ravioles'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Moldes para Huevos'
, 'slug' => str_slug( 'Moldes para Huevos'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bases para Huevo'
, 'slug' => str_slug( 'Bases para Huevo'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Glace'
, 'slug' => str_slug( 'Glace'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Flores y Figuras Pascua'
, 'slug' => str_slug( 'Flores y Figuras Pascua'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Moldes para Rosca'
, 'slug' => str_slug( 'Moldes para Rosca'
), 'rubro_id' => '4' ]);App\Subrubro::create(['name' =>  'Clips'
, 'slug' => str_slug( 'Clips'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Mojadedo '
, 'slug' => str_slug( 'Mojadedo '
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Tacos de Color'
, 'slug' => str_slug( 'Tacos de Color'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Cutters'
, 'slug' => str_slug( 'Cutters'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Colorantes Liquidos'
, 'slug' => str_slug( 'Colorantes Liquidos'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Porta Panchos'
, 'slug' => str_slug( 'Porta Panchos'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Glucosa'
, 'slug' => str_slug( 'Glucosa'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Porcelana Fria'
, 'slug' => str_slug( 'Porcelana Fria'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Pastillaje'
, 'slug' => str_slug( 'Pastillaje'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Pasta de Goma'
, 'slug' => str_slug( 'Pasta de Goma'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Polvo Pre Mezcla'
, 'slug' => str_slug( 'Polvo Pre Mezcla'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Porta Muffins'
, 'slug' => str_slug( 'Porta Muffins'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bandejas de Carton Gris'
, 'slug' => str_slug( 'Bandejas de Carton Gris'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Consorcio SUPER CONSORCIO'
, 'slug' => str_slug( 'Bolsas de Consorcio SUPER CONSORCIO'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Ensaladera'
, 'slug' => str_slug( 'Ensaladera'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas Emblocadas SUPOL'
, 'slug' => str_slug( 'Bolsas Emblocadas SUPOL'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Guirnaldas'
, 'slug' => str_slug( 'Guirnaldas'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Mani Saborizado'
, 'slug' => str_slug( 'Mani Saborizado'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Pasta para Modelar'
, 'slug' => str_slug( 'Pasta para Modelar'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Papel Picado'
, 'slug' => str_slug( 'Papel Picado'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Bandejas Doradas KP'
, 'slug' => str_slug( 'Bandejas Doradas KP'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Inflador de Globos'
, 'slug' => str_slug( 'Inflador de Globos'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Dulces'
, 'slug' => str_slug( 'Dulces'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bizcochuelos Mil Keiks'
, 'slug' => str_slug( 'Bizcochuelos Mil Keiks'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bizcochuelos Lyvian'
, 'slug' => str_slug( 'Bizcochuelos Lyvian'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Lapiz Tinta Comestible'
, 'slug' => str_slug( 'Lapiz Tinta Comestible'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Cubanitos'
, 'slug' => str_slug( 'Cubanitos'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Extracto de Malta'
, 'slug' => str_slug( 'Extracto de Malta'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Rollos Quimicos'
, 'slug' => str_slug( 'Rollos Quimicos'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Sobres de Papel KP'
, 'slug' => str_slug( 'Sobres de Papel KP'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Rollos de Papel Termico'
, 'slug' => str_slug( 'Rollos de Papel Termico'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Etiquetas Balanza'
, 'slug' => str_slug( 'Etiquetas Balanza'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Bizcochuelos NATALIA'
, 'slug' => str_slug( 'Bizcochuelos NATALIA'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Cinta Impresora'
, 'slug' => str_slug( 'Cinta Impresora'
), 'rubro_id' => '6' ]);App\Subrubro::create(['name' =>  'Obleas'
, 'slug' => str_slug( 'Obleas'
), 'rubro_id' => '5' ]);App\Subrubro::create(['name' =>  'Cerezas en Almibar'
, 'slug' => str_slug( 'Cerezas en Almibar'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Cortantes para Masa'
, 'slug' => str_slug( 'Cortantes para Masa'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Adhesivo Comestible'
, 'slug' => str_slug( 'Adhesivo Comestible'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Gelatina sin Sabor'
, 'slug' => str_slug( 'Gelatina sin Sabor'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bowl'
, 'slug' => str_slug( 'Bowl'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Duraznos'
, 'slug' => str_slug( 'Duraznos'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bandejas Plasticas BANDEX'
, 'slug' => str_slug( 'Bandejas Plasticas BANDEX'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bolsas de Carton Murillo'
, 'slug' => str_slug( 'Bolsas de Carton Murillo'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Humectante para torta'
, 'slug' => str_slug( 'Humectante para torta'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Papel para Bombones'
, 'slug' => str_slug( 'Papel para Bombones'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bolsas Riñon IMPORT'
, 'slug' => str_slug( 'Bolsas Riñon IMPORT'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Bandejas Plasticas Bisagra PFOOD'
, 'slug' => str_slug( 'Bandejas Plasticas Bisagra PFOOD'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Mani con Chocolate'
, 'slug' => str_slug( 'Mani con Chocolate'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bolsas de Carton Fantasia EVACOR'
, 'slug' => str_slug( 'Bolsas de Carton Fantasia EVACOR'
), 'rubro_id' => '1' ]);App\Subrubro::create(['name' =>  'Clavos para Hacer Flores'
, 'slug' => str_slug( 'Clavos para Hacer Flores'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Estecas'
, 'slug' => str_slug( 'Estecas'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Palos para Amasar'
, 'slug' => str_slug( 'Palos para Amasar'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Posatorta'
, 'slug' => str_slug( 'Posatorta'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Espatulas para Reposteria'
, 'slug' => str_slug( 'Espatulas para Reposteria'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Vaso Medidor'
, 'slug' => str_slug( 'Vaso Medidor'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Moldes de Aluminio'
, 'slug' => str_slug( 'Moldes de Aluminio'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Decoracion NAVIDAD'
, 'slug' => str_slug( 'Decoracion NAVIDAD'
), 'rubro_id' => '3' ]);App\Subrubro::create(['name' =>  'Set de Churros'
, 'slug' => str_slug( 'Set de Churros'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Colorantes Liposolubles'
, 'slug' => str_slug( 'Colorantes Liposolubles'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Fratachos'
, 'slug' => str_slug( 'Fratachos'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Cajas para Huevo'
, 'slug' => str_slug( 'Cajas para Huevo'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Lentejas de Chocolate'
, 'slug' => str_slug( 'Lentejas de Chocolate'
), 'rubro_id' => '2' ]);App\Subrubro::create(['name' =>  'Bolsas de Arranque en Rollo RENDIDOR'
, 'slug' => str_slug( 'Bolsas de Arranque en Rollo RENDIDOR'
), 'rubro_id' => '1' ]);
    }
}
